function menu
%Genero interfaz grafica
MenuPrincipal = figure('Units','normalized',...
              'Position',[.22 .4 .5 .18]);
          

Seccion2 = uipanel(MenuPrincipal,'Position',[.3 .02 .69 .95],...
                   'Title','Menu principal');
          
[x,map]=imread('logo.jpg');
I2=imresize(x, [60 113]);
h=uicontrol('style','pushbutton',...
            'Units','normalized',...
            'position',[0.08 0.6 0.13 0.33],...
            'cdata',I2)
        
int = uicontrol(MenuPrincipal,'Style','text',...
    'Units','normalized',...
    'String','Integrantes:',...
    'Position',[0.001 0.10 0.13 0.4]);
n1 = uicontrol(MenuPrincipal,'Style','text',...
    'Units','normalized',...
    'String','Camargo Emanuel',...
    'Position',[0.115 0.35 0.13 0.1]);
n2 = uicontrol(MenuPrincipal,'Style','text',...
    'Units','normalized',...
    'String','Elias Bazan',...
    'Position',[0.098 0.25 0.13 0.1]);
n3 = uicontrol(MenuPrincipal,'Style','text',...
    'Units','normalized',...
    'String','Ignacio Zurueta',...
    'Position',[0.11 0.15 0.13 0.1]);

Boton1 = uicontrol(Seccion2,'Style','pushbutton',...
    'Units','normalized',...
    'String','Grabar',...
    'CallBack',@Grabar,...
    'Position',[.13 .3 .3 .45]);

Boton2 = uicontrol(Seccion2,'Style','pushbutton',...
    'Units','normalized',...
    'String','Analisis de datos',...
    'CallBack',@Analisis,...
    'Position',[.56 .3 .3 .45]);
          


    function Grabar(src,event)
        close
        TPN1
    end

    function Analisis(src,event)
        close
        Interfazz
    end
end